# Generated by Django 5.2.8 on 2025-11-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSource',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Web Series', 'Web Series'), ('Book', 'Book')], max_length=20)),
                ('cover_image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tracker.quotesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tracker.quote')),
            ],
        ),
        migrations.AddIndex(
            model_name='quotesource',
            index=models.Index(fields=['user', 'title'], name='tracker_quo_user_id_8d9b89_idx'),
        ),
        migrations.AddIndex(
            model_name='quotesource',
            index=models.Index(fields=['user', 'type'], name='tracker_quo_user_id_3f7c11_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source', 'author'], name='tracker_quo_source__89ff13_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetag',
            index=models.Index(fields=['tag'], name='tracker_quo_tag_581511_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotetag',
            unique_together={('quote', 'tag')},
        ),
    ]
