# Generated by Django 5.2.8 on 2025-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
