# Generated by Django 5.2.8 on 2026-02-21 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_habit_scoringrule_dailyhabitscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='dailyhabitscore',
            new_name='tracker_dai_user_id_a68ed9_idx',
            old_name='tracker_dai_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='tracker_hab_user_id_7dbe30_idx',
            old_name='tracker_hab_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerblock',
            new_name='tracker_pla_user_id_c16105_idx',
            old_name='tracker_pla_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerlink',
            new_name='tracker_pla_user_id_ceb373_idx',
            old_name='tracker_pla_user_id_idx2',
        ),
        migrations.RenameIndex(
            model_name='plannertask',
            new_name='tracker_pla_block_i_a2a1a2_idx',
            old_name='tracker_pla_block_i_idx',
        ),
        migrations.RenameIndex(
            model_name='scoringrule',
            new_name='tracker_sco_user_id_b6ef11_idx',
            old_name='tracker_sco_user_id_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='tracker_use_user_id_c947fb_idx'),
        ),
    ]
