# Generated by Django 5.2.8 on 2026-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target',
            field=models.IntegerField(default=1),
        ),
    ]
