# Generated by Django 5.2.8 on 2026-09-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_goal_extended_fields'),
        ('tracker', '0010_goal_completed_tasks_goal_target'),
    ]

    operations = [
    ]
