# Generated by Django 5.2.8 on 2026-09-12 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_mood_water'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal_created', 'Goal Created'), ('goal_updated', 'Goal Updated'), ('goal_completed', 'Goal Completed'), ('goal_deleted', 'Goal Deleted'), ('planner_task_created', 'Planner Task Created'), ('planner_task_completed', 'Planner Task Completed'), ('planner_task_deleted', 'Planner Task Deleted'), ('habit_created', 'Habit Created'), ('habit_log', 'Habit Log'), ('achievement_earned', 'Achievement Earned'), ('expense_created', 'Expense Created'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('journal_updated', 'Journal Updated'), ('mood_logged', 'Mood Logged'), ('water_logged', 'Water Logged'), ('budget_created', 'Budget Created'), ('budget_exceeded', 'Budget Exceeded')], max_length=50)),
                ('subject_type', models.CharField(blank=True, help_text='Model name of the related object, e.g. "Goal"', max_length=100)),
                ('subject_id', models.CharField(blank=True, help_text='String id of the related object', max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event actually happened')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Optional structured extra data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='tracker_use_user_id_530183_idx'), models.Index(fields=['user', 'occurred_at'], name='tracker_use_user_id_54a616_idx'), models.Index(fields=['user', 'subject_type', 'subject_id'], name='tracker_use_user_id_5e7312_idx')],
            },
        ),
    ]
