# Generated by Django 5.2.8 on 2026-09-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_userevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivityAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habits_completed', models.IntegerField(default=0)),
                ('habits_total', models.IntegerField(default=0)),
                ('goals_completed', models.IntegerField(default=0)),
                ('goals_created', models.IntegerField(default=0)),
                ('planner_tasks_completed', models.IntegerField(default=0)),
                ('planner_tasks_created', models.IntegerField(default=0)),
                ('has_journal', models.BooleanField(default=False)),
                ('mood', models.CharField(blank=True, default='', max_length=20)),
                ('water_glasses', models.IntegerField(default=0)),
                ('water_target', models.IntegerField(default=0)),
                ('expense_count', models.IntegerField(default=0)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points', models.IntegerField(default=0)),
                ('achievements_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracker_dai_user_id_1f0026_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
