# Generated by Django 5.2.8 on 2026-09-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_dailyactivityaggregate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'category'],
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='trigger_rule',
            field=models.JSONField(blank=True, default=dict, help_text='Optional rule describing what measurable event triggers this achievement, e.g. {"event_type": "planner_task_completed", "count": 7}'),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(blank=True, help_text='Goal this habit supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='tracker.goal'),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='goal',
            field=models.ForeignKey(blank=True, help_text='Goal this task contributes to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_tasks', to='tracker.goal'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['goal'], name='tracker_hab_goal_id_da8396_idx'),
        ),
        migrations.AddIndex(
            model_name='plannertask',
            index=models.Index(fields=['goal'], name='tracker_pla_goal_id_84e4b9_idx'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'year', 'month'], name='tracker_bud_user_id_aa29c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'year', 'month')},
        ),
    ]
