# Generated by Django 5.2.8 on 2026-09-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_budget_achievement_trigger_rule_habit_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_dates',
            field=models.JSONField(blank=True, default=list, help_text='ISO dates the habit was completed'),
        ),
        migrations.AddField(
            model_name='habit',
            name='grace_period',
            field=models.IntegerField(default=0, help_text='Missed-day grace before streak breaks'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminders',
            field=models.JSONField(blank=True, default=list, help_text='Optional reminder config list'),
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list, help_text='Weekdays (0=Mon..6=Sun) for weekly/custom schedules'),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current consecutive-day streak'),
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['goal', 'order'], name='tracker_goa_goal_id_acb370_idx')],
            },
        ),
    ]
