# Generated by Django 5.2.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_habit_completed_dates_habit_grace_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Snapshot of blocks/tasks/links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'recurrence'], name='tracker_goa_user_id_169294_idx'),
        ),
        migrations.AddIndex(
            model_name='plannertask',
            index=models.Index(fields=['due_date'], name='tracker_pla_due_dat_38ce5f_idx'),
        ),
        migrations.AddField(
            model_name='plannertemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='plannertemplate',
            index=models.Index(fields=['user'], name='tracker_pla_user_id_8b0a18_idx'),
        ),
    ]
