# Generated by Django 5.2.8 on 2026-09-12 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_account_budgetalert_income_recurringexpense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_deadline_enabled', models.BooleanField(default=True)),
                ('habit_reminder_enabled', models.BooleanField(default=True)),
                ('budget_alert_enabled', models.BooleanField(default=True)),
                ('streak_alert_enabled', models.BooleanField(default=True)),
                ('achievement_enabled', models.BooleanField(default=True)),
                ('weekly_summary_enabled', models.BooleanField(default=True)),
                ('monthly_summary_enabled', models.BooleanField(default=True)),
                ('recurring_transaction_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (24h format)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (24h format)', null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('goal_deadline', 'Goal Deadline'), ('habit_reminder', 'Habit Reminder'), ('budget_alert', 'Budget Alert'), ('streak_alert', 'Streak Alert'), ('achievement_earned', 'Achievement Earned'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('recurring_transaction', 'Recurring Transaction'), ('system', 'System')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra context data')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='tracker_not_user_id_57a19e_idx'), models.Index(fields=['user', 'type'], name='tracker_not_user_id_db5f09_idx'), models.Index(fields=['user', 'created_at'], name='tracker_not_user_id_59d3e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeduplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=30)),
                ('dedupe_key', models.CharField(help_text='Unique key for deduplication (e.g., goal_id, habit_id)', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dedupes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'notification_type'], name='tracker_not_user_id_8f6de5_idx'), models.Index(fields=['sent_at'], name='tracker_not_sent_at_41f79d_idx')],
                'unique_together': {('user', 'notification_type', 'dedupe_key')},
            },
        ),
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('gift', 'Gift'), ('refund', 'Refund'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly frequency (1-31)', null=True)),
                ('next_occurrence', models.DateField(help_text='Next date this recurring income should be created')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_occurrence'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tracker_rec_user_id_21e721_idx'), models.Index(fields=['next_occurrence'], name='tracker_rec_next_oc_e49f1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('goal_deadline_check', 'Goal Deadline Check'), ('habit_reminder', 'Habit Reminder'), ('budget_alert_check', 'Budget Alert Check'), ('streak_alert_check', 'Streak Alert Check'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('recurring_expense_process', 'Recurring Expense Process'), ('recurring_income_process', 'Recurring Income Process'), ('subscription_billing', 'Subscription Billing')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Job-specific data')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Job result data')),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='tracker_sch_status_2b92d4_idx'), models.Index(fields=['job_type', 'status'], name='tracker_sch_job_typ_968e64_idx'), models.Index(fields=['user', 'status'], name='tracker_sch_user_id_c3dd3f_idx')],
            },
        ),
    ]
