# Generated by Django 5.2.8 on 2026-09-13 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_add_ai_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('goal', 'Goal'), ('habit', 'Habit'), ('person', 'Person'), ('event', 'Event'), ('note', 'Note'), ('summary', 'Conversation Summary')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('entities', models.JSONField(blank=True, default=dict, help_text='Extracted entities (people, dates, amounts, etc.)')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expiry (P8-10)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='tracker.aiconversation')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories_created', to='tracker.aimessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMemorySummarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_message_count', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarizations', to='tracker.aiconversation')),
                ('summary_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarizations', to='tracker.aimemory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_length', models.CharField(choices=[('brief', 'Brief'), ('normal', 'Normal'), ('detailed', 'Detailed')], default='normal', max_length=20)),
                ('auto_execute_tools', models.BooleanField(default=False, help_text='Auto-execute non-destructive tools')),
                ('include_context_summary', models.BooleanField(default=True, help_text='Include conversation summary in context')),
                ('memory_enabled', models.BooleanField(default=True, help_text='Enable memory system')),
                ('memory_retention_days', models.IntegerField(default=90, help_text='Days to retain memory entries')),
                ('max_memory_entries', models.IntegerField(default=1000, help_text='Maximum memory entries per user')),
                ('notify_on_tool_execution', models.BooleanField(default=False)),
                ('notify_on_memory_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
        migrations.AddIndex(
            model_name='aimemory',
            index=models.Index(fields=['user', 'is_active', 'memory_type'], name='tracker_aim_user_id_2edcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemory',
            index=models.Index(fields=['user', 'is_active', 'priority'], name='tracker_aim_user_id_5f9b88_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemory',
            index=models.Index(fields=['user', 'expires_at'], name='tracker_aim_user_id_b05663_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemory',
            index=models.Index(fields=['conversation'], name='tracker_aim_convers_c5031b_idx'),
        ),
    ]
