# Generated by Django 5.2.8 on 2026-09-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_add_memory_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('completeness', 'Completeness'), ('uniqueness', 'Uniqueness'), ('validity', 'Validity'), ('consistency', 'Consistency'), ('freshness', 'Freshness'), ('outliers', 'Outliers')], max_length=20)),
                ('domain', models.CharField(blank=True, help_text='Which domain was checked (expenses, habits, etc.)', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('total_records', models.IntegerField(default=0)),
                ('valid_records', models.IntegerField(default=0)),
                ('invalid_records', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed findings')),
                ('message', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_quality_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'check_type'], name='tracker_mld_user_id_f6f5af_idx'), models.Index(fields=['user', 'domain'], name='tracker_mld_user_id_ae1814_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('expenses', 'Expenses'), ('habits', 'Habits'), ('goals', 'Goals'), ('mood', 'Mood'), ('journal', 'Journal'), ('water', 'Water'), ('combined', 'Combined')], max_length=20)),
                ('split', models.CharField(choices=[('train', 'Train'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('records_count', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature names included')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'data_type'], name='tracker_mld_user_id_31284b_idx'), models.Index(fields=['user', 'split'], name='tracker_mld_user_id_167481_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('numerical', 'Numerical'), ('categorical', 'Categorical'), ('boolean', 'Boolean'), ('temporal', 'Temporal'), ('aggregate', 'Aggregate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_domains', models.JSONField(blank=True, default=list, help_text='Which tracker domains this feature derives from')),
                ('computation_logic', models.TextField(blank=True, help_text='Description or code snippet of how feature is computed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tracker_mlf_user_id_0d28ef_idx')],
            },
        ),
    ]
