# Generated by Django 5.2.8 on 2026-09-14 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_ml_p9_01_03'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLHabitConsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_id', models.CharField(blank=True, default='', max_length=100)),
                ('habit_name', models.CharField(blank=True, default='', max_length=255)),
                ('prediction_date', models.DateField()),
                ('likelihood_of_miss', models.FloatField(default=0.0, help_text='Probability 0-1 that habit will be missed')),
                ('contributing_factors', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_habit_consistency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['user', 'habit_id', 'prediction_date'], name='tracker_mlh_user_id_4fe1f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLSpendingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_spending_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'category', 'period_start'], name='tracker_mls_user_id_e68e12_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLTransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('predicted_category', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('alternative_categories', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_transaction_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'predicted_category'], name='tracker_mlt_user_id_16b367_idx')],
            },
        ),
    ]
