# Generated by Django 5.2.8 on 2026-09-14 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_ml_p9_04_06'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('spending', 'Spending'), ('habit', 'Habit'), ('goal', 'Goal'), ('activity', 'Activity'), ('financial', 'Financial')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('detected_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('expected_range_low', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('expected_range_high', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'anomaly_type', 'is_resolved'], name='tracker_mla_user_id_8213e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLGoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.CharField(blank=True, default='', max_length=100)),
                ('goal_text', models.CharField(blank=True, default='', max_length=500)),
                ('predicted_probability', models.FloatField(default=0.0, help_text='Probability 0-1 of completion')),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('remaining_days', models.IntegerField(default=0)),
                ('contributing_factors', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_goal_completion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-predicted_probability'],
                'indexes': [models.Index(fields=['user', 'goal_id'], name='tracker_mlg_user_id_6756b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLRecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('expense', 'Expense'), ('habit', 'Habit'), ('goal', 'Goal'), ('productivity', 'Productivity'), ('finance', 'Finance'), ('general', 'General')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_recommendation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['user', 'rank_type', 'rank'], name='tracker_mlr_user_id_39f706_idx')],
            },
        ),
    ]
