# Generated by Django 5.2.8 on 2026-09-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_ml_p9_07_09'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('metric_type', models.CharField(choices=[('accuracy', 'Accuracy'), ('precision', 'Precision'), ('recall', 'Recall'), ('f1', 'F1 Score'), ('auc_roc', 'AUC-ROC'), ('rmse', 'RMSE'), ('mae', 'MAE'), ('r2', 'R²')], max_length=20)),
                ('value', models.FloatField(default=0.0)),
                ('dataset_name', models.CharField(blank=True, default='', max_length=255)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'indexes': [models.Index(fields=['user', 'model_name', 'model_version'], name='tracker_mle_user_id_533002_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModelMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('monitor_type', models.CharField(choices=[('data_drift', 'Data Drift'), ('concept_drift', 'Concept Drift'), ('performance_degradation', 'Performance Degradation'), ('feature_importance_shift', 'Feature Importance Shift')], max_length=30)),
                ('alert_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('current_value', models.FloatField(default=0.0)),
                ('baseline_value', models.FloatField(default=0.0)),
                ('threshold', models.FloatField(default=0.1)),
                ('message', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'model_name', 'monitor_type'], name='tracker_mlm_user_id_7620a3_idx'), models.Index(fields=['user', 'alert_level'], name='tracker_mlm_user_id_7d9efa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('training_data_set', models.CharField(blank=True, default='', max_length=255)),
                ('features_used', models.JSONField(blank=True, default=list)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('performance_metrics', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'model_name'], name='tracker_mlm_user_id_c8c41a_idx'), models.Index(fields=['user', 'model_name', 'version'], name='tracker_mlm_user_id_aac9f8_idx')],
            },
        ),
    ]
