# Generated by Django 5.2.8 on 2026-09-14 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_ml_p9_10_12'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedPersonalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(blank=True, default=dict, help_text='Comprehensive user state including all domains')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('financial_health', models.FloatField(default=0.0)),
                ('goal_progress', models.FloatField(default=0.0)),
                ('habit_consistency', models.FloatField(default=0.0)),
                ('mood_trend', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrossDomainReasoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning_type', models.CharField(choices=[('correlation', 'Correlation'), ('causal', 'Causal'), ('pattern', 'Pattern'), ('trend', 'Trend'), ('comparison', 'Comparison')], max_length=20)),
                ('domains_involved', models.JSONField(blank=True, default=list, help_text='List of domains analyzed')),
                ('insight', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('supporting_evidence', models.JSONField(blank=True, default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_domain_reasoning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reasoning_type'], name='tracker_cro_user_id_e7c262_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('habit', 'Habit'), ('goal', 'Goal'), ('expense', 'Expense'), ('productivity', 'Productivity'), ('finance', 'Finance'), ('wellness', 'Wellness'), ('general', 'General')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_title', models.CharField(blank=True, default='', max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True, help_text='Why this recommendation exists')),
                ('action_suggested', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['user', 'rec_type', 'rank'], name='tracker_ran_user_id_85cbb8_idx')],
            },
        ),
    ]
