# Generated by Django 5.2.8 on 2026-09-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_p10_04_06'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan_data', models.JSONField(blank=True, default=dict, help_text='Plan items with tasks, habits, goals')),
                ('overall_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('generated_by_model', models.CharField(blank=True, default='', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracker_dai_user_id_da001b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('priorities', models.JSONField(blank=True, default=list, help_text='List of priority items for the week')),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('key_goals', models.JSONField(blank=True, default=list)),
                ('risk_mitigations', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('generated_by_model', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['user', 'week_start_date'], name='tracker_wee_user_id_65e569_idx')],
            },
        ),
    ]
