# Generated by Django 5.2.8 on 2026-09-14 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_p10_09_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('prediction', 'Prediction'), ('insight', 'Insight'), ('intervention', 'Intervention')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('explanation_text', models.TextField()),
                ('reasoning_steps', models.JSONField(blank=True, default=list, help_text='Step-by-step reasoning')),
                ('supporting_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'explanation_type'], name='tracker_exp_user_id_db9cde_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('intervention', 'Intervention'), ('prediction', 'Prediction'), ('insight', 'Insight')], max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('partially_accepted', 'Partially Accepted'), ('skipped', 'Skipped')], max_length=20)),
                ('feedback_text', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0, help_text='User-rated relevance 0-1')),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'feedback_type', 'action'], name='tracker_use_user_id_bd27d2_idx')],
            },
        ),
    ]
